version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: pg-fitdiary
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./server-pgdata/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fitdiary-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@postgres:5432/fitdiary?schema=public
    depends_on:
      - postgres
    restart: unless-stopped