name: Deploy to VDS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma client
      run: cd apps/fitdiary-api && npx prisma generate

    - name: Build project
      run: npm run build

    - name: Copy files to VDS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        port: ${{ secrets.VDS_PORT }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_SSH_KEY }}
        source: "apps/fitdiary-api/dist/*, docker-compose.yml, dockerfile, apps/fitdiary-api/package.json, apps/fitdiary-api/prisma/*, apps/fitdiary-api/prisma/migrations/*"
        target: "~/fit-diary-api"

    - name: Create .env file on VDS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        port: ${{ secrets.VDS_PORT }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          cd ~/fit-diary-api
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_URL=postgresql://postgres:${{ secrets.DB_PASSWORD }}@postgres:5432/fitdiary?schema=public" >> .env
          echo "PORT=3000" >> .env

    - name: Fix permissions on VDS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        port: ${{ secrets.VDS_PORT }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          sudo chown -R 1000:1000 ~/fit-diary-api/server-pgdata/pgdata
          sudo chmod -R 755 ~/fit-diary-api/server-pgdata/pgdata

    - name: Check files in target directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        port: ${{ secrets.VDS_PORT }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          cd ~/fit-diary-api
          ls -la
          cat docker-compose.yml

    - name: Deploy to VDS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        port: ${{ secrets.VDS_PORT }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          cd ~/fit-diary-api
          docker compose config
          docker compose down
          docker compose up --build -d
